export const GET_EPISODES = 'GET_EPISODES';
export const GET_SINGLE_EPISODE = 'GET_SINGLE_EPISODE';
export const EPISODES_ERROR = 'EPISODES_ERROR';

export const GET_CHARACTERS = 'GET_CHARACTERS';
export const GET_SINGLE_CHARACTER = 'GET_SINGLE_CHARACTER';
export const CHARACTERS_ERROR = 'CHARACTERS_ERROR';
